# fly.toml app configuration file generated for sas-api on 2023-12-11T22:22:40+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sas-api"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
